parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(DATABASE_URL): ''

doctrine_mongodb:
    connections:
        default:
            server: "mongodb://localhost:27017"
            options: {}
    default_database: dbfullstack
    document_managers:
        default:
            auto_mapping: true
            mappings:
                App:
                    is_bundle: false
                    type: annotation
                    dir: '%kernel.project_dir%/src/Politicians/Domain'
                    prefix: 'App\Politicians\Domain'
                    alias: App