version: '3.4'

services:
  php:
    #    image: api-backend
    build:
      context: ./
    #      target: backend
    depends_on:
    - mongodb
    env_file:
    - ./.env
    volumes:
    - .:/var/www:rw
    ports:
    - "8080:80"
    links:
    - mongodb
  mongodb:
    build:
      context: ./docker/mongo
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    ports:
      - "27017:27017"