<?php
/**
 * Created by PhpStorm.
 * User: JorgePc
 * Date: 27/01/2019
 * Time: 16:29
 */

namespace App;
use League\Tactician\Bundle\TacticianBundle;

use Symfony\Component\Console\Application;
use Symfony\Component\DependencyInjection\ContainerBuilder;
use Symfony\Component\HttpKernel\Bundle\Bundle;
class App extends Bundle
{
    public function __construct()
    {

    }

    public function registerBundles()
    {


    }

    public function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
    }

    public function shutdown()
    {
        parent::shutdown(); // TODO: Change the autogenerated stub
    }

    public function build(ContainerBuilder $container)
    {
        parent::build($container); // TODO: Change the autogenerated stub
    }

    public function getContainerExtension()
    {
        return parent::getContainerExtension(); // TODO: Change the autogenerated stub
    }

    public function getNamespace()
    {
        return parent::getNamespace(); // TODO: Change the autogenerated stub
    }

    public function getPath()
    {
        return parent::getPath(); // TODO: Change the autogenerated stub
    }

    public function registerCommands(Application $application)
    {
        parent::registerCommands($application); // TODO: Change the autogenerated stub
    }

    protected function getContainerExtensionClass()
    {
        return parent::getContainerExtensionClass(); // TODO: Change the autogenerated stub
    }

    protected function createContainerExtension()
    {
        return parent::createContainerExtension(); // TODO: Change the autogenerated stub
    }
}